In [20]:
# target parameter attack on linear regression with close form solution on the cross derivative

import os
import time
import torch
from torch import nn
import torch.nn.functional as F
import torch.optim as optim
from models import *
from torch.autograd import Variable
from torchvision import datasets, transforms
from torch.utils.data import Dataset, DataLoader
from numpy import linalg as LA
import numpy as np

torch.manual_seed(0)
device = 'cuda'

In [21]:
num_inputs = 1
num_outputs = 1
num_examples_train = 10000
num_examples_test = 5000
dtype = torch.float

def real_fn(X):
    return 2 * X + 4.2
    #return 2 * X[:, 0] - 3.4 * X[:, 1] + 4.2

# define training set
X_train = torch.randn(num_examples_train, num_inputs, device=device, dtype=dtype)
noise_train = .1 * torch.randn(num_examples_train, num_inputs, device=device, dtype=dtype)
y_train = (real_fn(X_train) + noise_train)

X_test = torch.randn(num_examples_test, num_inputs, device=device, dtype=dtype)
noise_test = .1 * torch.randn(num_examples_test, num_inputs, device=device, dtype=dtype)
y_test = (real_fn(X_test) + noise_test)

In [22]:
class LinearDataset(Dataset):
    def __init__(self, X, y):
        assert X.size()[0] == y.size()[0]
        self.X = X
        self.y = y
    
    def __len__(self):
        return self.X.size()[0]
    
    def __getitem__(self, idx):
        return [self.X[idx], self.y[idx]]

In [23]:
batch_size = 10000
train_data = DataLoader(LinearDataset(X_train, y_train), batch_size=batch_size, shuffle=False)
test_data = DataLoader(LinearDataset(X_test, y_test), batch_size=batch_size, shuffle=True)

In [24]:
class LinearRegression(nn.Module):
    def __init__(self, **kwargs):
        super(LinearRegression, self).__init__(**kwargs)
        self.fc1 = nn.Linear(1, 1)
        
    def forward(self, x):
        x = self.fc1(x)
        return x
    
model = LinearRegression()
model.to(device)
model.load_state_dict(torch.load("models/linear_gd.pt"))

<All keys matched successfully>

In [126]:
# the script for training target attack
epsilon = 1

def autograd(outputs, inputs, create_graph=False):
    """Compute gradient of outputs w.r.t. inputs, assuming outputs is a scalar."""
    #inputs = tuple(inputs)
    grads = torch.autograd.grad(outputs, inputs, create_graph=create_graph, allow_unused=True)
    return [xx if xx is not None else yy.new_zeros(yy.size()) for xx, yy in zip(grads, inputs)]

def train(epoch):
    for batch_idx, (data, target) in enumerate(train_data):
        data, target = data.to(device), target.to(device)
        data.requires_grad=True
        if epoch==0:
            # initialize poisoned data
            data_p = Variable(data[:(int(epsilon*len(data)))])
            target_p = Variable(target[:(int(epsilon*len(target)))])
            max_value = torch.max(data_p)
            min_value = torch.min(data_p)
            torch.save(target_p,'target_p_linear.pt')
        else:
            data_p = torch.load('data_p_linear.pt')
            target_p = torch.load('target_p_linear.pt')
            max_value = torch.max(data_p)
            min_value = torch.min(data_p)
        data_p.requires_grad=True
    
        # initialize f function
        criterion = nn.MSELoss()
        
        # calculate gradient of w on clean sample
        output_c = model(data.view(data.size(0), -1))
        loss_c =  0.5 * criterion(output_c,target)
        
        # calculate dL/dg_1
        grad_c= autograd(loss_c,tuple(model.parameters()),create_graph=True)
        g1 = torch.cat((grad_c[0],grad_c[1].unsqueeze(0)),0)
        
        # calculate gradient of w on poisoned sample
        output_p = model(data_p.view(data_p.size(0), -1))
        loss_p = 0.5 * criterion(output_p,target_p)
        grad_p= autograd(loss_p,tuple(model.parameters()),create_graph=True)
        g2 = torch.cat((grad_p[0],grad_p[1].unsqueeze(0)),0)
        
        # calculate the true loss: |g_c + g_p|_{inf}
        grad_sum = g1+g2
        
        loss = torch.norm(grad_sum,2)
        
        dldg2 = torch.autograd.grad(loss,g2,create_graph=True)
        dldg2 = torch.stack(list(dldg2),dim=0)
        dldg2 = dldg2.squeeze(0)
        
        # first approach is to calculate the update in closed form 
        l = []
        for param in model.parameters():
            l.append(param)
        # extract w and b
        w = torch.cat((l[0],l[1].unsqueeze(0)))
        
        update = torch.matmul(data_p,torch.matmul(w.t(),dldg2))
        identity = torch.ones(len(data_p),2)
        identity = identity.to('cuda')
        update1 = - torch.matmul((output_p - target_p)*identity,dldg2)
        #print("approach 1 update:{}".format(update1))
        
        # Still bugs in Approach 2 and 3, needs to be fixed
        # second approach is to use torch.autograd.functional.hessian to calculate the update
        Xw_input = torch.cat((data_p,w[0].unsqueeze(0).t()),0)
        def function_f(x):
            y_hat = torch.matmul(x[:(len(x)-1)],x[(len(x)-1):].t())+w[1]
            return(0.5 * criterion(y_hat,target_p))
        f_x = function_f(Xw_input)
        hessian = torch.autograd.functional.hessian(function_f, Xw_input)
        hessian_wx = hessian[len(Xw_input)-1]
        hessian_wx = hessian_wx.squeeze(0)        
            
        update2 = torch.matmul(hessian_wx,dldg2[0]).unsqueeze(1)
        print("approach2 update:{}".format(update2))
        
        # third approach is to use torch.autograd.functional.hvp to calculate the update
        v = torch.ones(len(data_p)+1,1) 
        v = v.to('cuda')
        v = v * dldg2[0]
        v[len(v)-1] = 0
        update3 = torch.autograd.functional.hvp(function_f,Xw_input,v)
        print(update3[1])
        
        # to use approach 1:
        #data_t = data_p + update1
        
        # to use approach 2:
        data_t = data_p + update2[:len(update2)-1]
        #data_t = torch.clamp(data_t,min_value.item(),max_value.item())
        #print("data change:{}".format(torch.mean(data_t-data_p)))
        torch.save(data_t, 'data_p_linear.pt')
        
        print("epoch:{},loss:{}".format(epoch, loss))
        

In [127]:
for epoch in range(100):
    train(epoch)

approach2 update:tensor([[ 6.0077e-06],
        [-2.1764e-05],
        [ 9.3778e-05],
        ...,
        [-4.9321e-05],
        [-4.4570e-05],
        [-4.4095e-01]], device='cuda:0', grad_fn=<UnsqueezeBackward0>)
tensor([[-1.0692e-04],
        [-1.0692e-04],
        [-1.0692e-04],
        ...,
        [-1.0692e-04],
        [-1.0692e-04],
        [-3.9847e-01]], device='cuda:0')
epoch:0,loss:2.041837692260742
approach2 update:tensor([[ 6.0075e-06],
        [-2.1763e-05],
        [ 9.3775e-05],
        ...,
        [-4.9320e-05],
        [-4.4569e-05],
        [-4.4096e-01]], device='cuda:0', grad_fn=<UnsqueezeBackward0>)
tensor([[-1.0693e-04],
        [-1.0693e-04],
        [-1.0693e-04],
        ...,
        [-1.0693e-04],
        [-1.0693e-04],
        [-3.9846e-01]], device='cuda:0')
epoch:1,loss:2.0418219566345215


KeyboardInterrupt: 

In [262]:
b = torch.ones(int(num_examples_train*epsilon))
b = b.unsqueeze(1)
b = b.to('cuda')
# absorb b into the input so it matches the weights in tensors
X_p_b = torch.cat((data_p,b),1)
Xw_input = torch.cat((X_p_b,w.t()),0)

In [ ]:
# random tests, may be useful
criterion = nn.MSELoss()
a = torch.ones(3)
inputs = torch.ones(10, 1)
def function_f(x):
    y_hat = torch.matmul(x[:(len(x)-1)],x[(len(x)-1):].t())
    return(criterion(y_hat,a))
function_f(inputs)
print(torch.autograd.functional.hessian(function_f, inputs)[2].size())

In [67]:
def pow_reducer(x):
    return x.pow(3).sum()
    
inputs1 = torch.rand(2,2)
inputs2 = torch.rand(1,2)
print(6*inputs1)
print(6*inputs2)
#inputs2 = inputs1[0]
#a = torch.ones(1,2)
#b = torch.zeros(2,2)
#v = torch.cat((b,a.t()),0)
print(pow_reducer(inputs1))
print(torch.autograd.functional.hessian(pow_reducer, inputs1))
print(torch.autograd.functional.hessian(pow_reducer, inputs2))
#torch.autograd.functional.hvp(pow_reducer, inputs,v)

tensor([[0.8822, 1.5141],
        [0.5289, 4.5655]])
tensor([[2.6943, 5.3088]])
tensor(0.4605)
tensor([[[[0.8822, 0.0000],
          [0.0000, 0.0000]],

         [[0.0000, 1.5141],
          [0.0000, 0.0000]]],


        [[[0.0000, 0.0000],
          [0.5289, 0.0000]],

         [[0.0000, 0.0000],
          [0.0000, 4.5655]]]])
tensor([[[[2.6943, 0.0000]],

         [[0.0000, 5.3088]]]])


In [ ]:
l = []
for param in model.parameters():
    l.append(param)

# extract w and b
w = torch.cat((l[0],l[1].unsqueeze(0)),0)
print(w.t().size())

b = torch.ones(num_examples_train)
b = b.unsqueeze(1)
b = b.to('cuda')

# absorb b into weights
X_train_b = torch.cat((X_train,b),1)
print(X_train_b.size())

# retrieve prediction using matrix multiplication
y_hat = torch.matmul(X_train_b,w)
print(y_hat)

In [263]:
l = []
for param in model.parameters():
    l.append(param)

# extract w and b
w = torch.cat((l[0],l[1].unsqueeze(0)),0)
print(w.t().size())

b = torch.ones(num_examples_train)
b = b.unsqueeze(1)
b = b.to('cuda')

# absorb b into weights
X_train_b = torch.cat((X_train,b),1)
print(X_train_b.size())

# retrieve prediction using matrix multiplication
y_hat = torch.matmul(X_train_b,w)
print(y_hat)

torch.Size([1, 2])
torch.Size([10000, 2])
tensor([[3.6727],
        [4.4504],
        [0.9949],
        ...,
        [5.0574],
        [5.3945],
        [5.1862]], device='cuda:0', grad_fn=<MmBackward>)
